name: Run Tests
on:
  pull_request:
    types: [opened, edited, synchronize]
    paths:
      - digi_log_fe/**
      - .github/test-frontend.yml
  workflow_dispatch:
concurrency:
  group: general-build-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digi_log_fe
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - run: npm ci
      - run: npm run test:prod
      - run: npm run lint