name: Run Tests
on:
  pull_request:
    types: [opened, edited, synchronize]
    paths:
      - digi_log_fe/**
      - .github/workflows/test-frontend.yml
  workflow_dispatch:
concurrency:
  group: frontend-test-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: willcaul/jest-github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: "digi_log_fe"